language: python
python:
    - "3.4"
    - "3.5"
install:
    - pip install -r requirements/development.txt
script:
    - pep8 .
notifications:
      slack: goubuntu:FcMk2XYzWOXJT0wfCnq4qkeQ

      email: 
        - feanar729@gmail.com
        - khwalex@gmail.com
        - tjalwled12@gmai.com
# blacklist
branches:
    except:
        - master
# whitelist
branches:
    except:
        - develop
        - feature/init
